### ISSUE TITLE
Star catalog inputs not safe?

### ISSUE THREAD

**Issue by sidneymau** [des-science/montara#21]
To get the stellar catalogs to work, I found that I need to change the following line in `montara/des_tile.py` because `desstar_safe` was not in the GalSim config dictionary. As far as I'm aware, this isn't a huge problem, but wanted to flag it before submitting a pull request.

```
diff --git a/montara/des_tile.py b/montara/des_tile.py
index fa74ef5..b1d6374 100644
--- a/montara/des_tile.py
+++ b/montara/des_tile.py
@@ -554,7 +554,7 @@ class DESTileBuilder(OutputBuilder):
                     field = base['input'][key]
                     loader = galsim.config.input.valid_input_types[key]
                     if (key in base['_input_objs'] and
-                            base['_input_objs']['desstar' + '_safe'][0]):
+                            base['_input_objs']['desstar'][0]):
                         star_input = base["_input_objs"][key][0]
                     else:
                         kwargs, safe = loader.getKwargs(field, base, logger)
```

**Comment by sidneymau** [comment]
My guess is that this is happening due to https://github.com/des-science/montara/blob/main/montara/des_tile.py#L174-L179

**Comment by beckermr** [comment]
@rmjarvis Can you look at this?

**Comment by rmjarvis** [comment]
I don't know about this change in particular.  But I think you shouldn't ever be accessing `base['_input_objs']` by hand.  Does galsim.config.GetInputObj not do what you need?

**Comment by beckermr** [comment]
@sidneymau whats the status of this issue? I want to cut new versions of the sims packages and install them at nersc.

**Comment by sidneymau** [comment]
No progress as I haven't been doing any testing with stars lately. I was going to try and work on this tonight but am having problems with the hotel wifi. I can keep layering my own montara install over the environment if you want to update the packages.

**Comment by beckermr** [comment]
Note you'll need to update your branch to get the latest changes

**Comment by beckermr** [comment]
Can we get a PR for this fix so we can move aheaD?
